#pragma once

#include "sfse_common/BranchTrampoline.h"
#include "sfse_common/BufferStream.h"
#include "sfse_common/CoreInfo.h"
#include "sfse_common/DataStream.h"
#include "sfse_common/DirectoryIterator.h"
#include "sfse_common/Errors.h"
#include "sfse_common/FileStream.h"
#include "sfse_common/Log.h"
#include "sfse_common/Relocation.h"
#include "sfse_common/SafeWrite.h"
#include "sfse_common/sfse_version.h"
#include "sfse_common/Types.h"
#include "sfse_common/Utilities.h"

#include "sfse/GameConsole.h"
#include "sfse/GameData.h"
#include "sfse/GameEvents.h"
#include "sfse/GameMenu.h"
//#include "sfse/GameObjects.h"
#include "sfse/GameReferences.h"
#include "sfse/GameScript.h"
#include "sfse/GameSettings.h"
#include "sfse/GameSingleton.h"
#include "sfse/GameTypes.h"
#include "sfse/GameUI.h"
#include "sfse/PluginManager.h"
#include "sfse/PluginAPI.h"

#include "xbyak/xbyak.h"